-- Drop existing tables if they exist
DROP TABLE IF EXISTS public.study_tasks;
DROP TABLE IF EXISTS public.applications;

-- Create applications table first (referenced by study_tasks)
CREATE TABLE public.applications (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    university text not null,
    program text not null,
    country text not null,
    deadline date not null,
    status text check (status in ('planning', 'in-progress', 'submitted', 'interview', 'accepted', 'rejected', 'waitlisted')),
    notes text,
    reminder boolean default false,
    reminder_date timestamp with time zone,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Enable RLS for applications
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own applications" ON public.applications
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own applications" ON public.applications
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own applications" ON public.applications
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own applications" ON public.applications
    FOR DELETE USING (auth.uid() = user_id);

-- Create study_tasks table
CREATE TABLE public.study_tasks (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users not null,
    task text not null,
    subject text not null,
    date date not null,
    completed boolean default false,
    priority text check (priority in ('low', 'medium', 'high')),
    estimated_hours numeric default 1,
    source text default 'study',
    application_id bigint references public.applications(id) on delete set null,
    reminder boolean default false,
    reminder_date timestamp with time zone,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Enable RLS for study_tasks
ALTER TABLE public.study_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own tasks" ON public.study_tasks
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own tasks" ON public.study_tasks
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own tasks" ON public.study_tasks
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own tasks" ON public.study_tasks
    FOR DELETE USING (auth.uid() = user_id);

-- Create application_tasks table (referenced in the frontend types)
CREATE TABLE public.application_tasks (
    id bigint generated by default as identity primary key,
    application_id bigint references public.applications(id) on delete cascade not null,
    task text not null,
    completed boolean default false,
    due_date date,
    reminder boolean default false,
    reminder_date timestamp with time zone,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Enable RLS for application_tasks
ALTER TABLE public.application_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own application tasks" ON public.application_tasks
    FOR SELECT USING (
        exists (
            select 1 from public.applications
            where applications.id = application_tasks.application_id
            and applications.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can insert their own application tasks" ON public.application_tasks
    FOR INSERT WITH CHECK (
        exists (
            select 1 from public.applications
            where applications.id = application_tasks.application_id
            and applications.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can update their own application tasks" ON public.application_tasks
    FOR UPDATE USING (
        exists (
            select 1 from public.applications
            where applications.id = application_tasks.application_id
            and applications.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can delete their own application tasks" ON public.application_tasks
    FOR DELETE USING (
        exists (
            select 1 from public.applications
            where applications.id = application_tasks.application_id
            and applications.user_id = auth.uid()
        )
    );
